name: Run

on:
  workflow_dispatch:
  repository_dispatch:
  schedule:
    - cron: 0 */6 * * *

jobs:
  build:

    if: github.actor == github.repository_owner
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@main
    - name: Run
      uses: GabrielBB/xvfb-action@v1
      with:
        run: dotnet run
      env: 
        CONF: ${{ secrets.CONF }}
